##============= JPA and Hibernate Configuration ========#
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
#============== Postgres DB (Auth) ======================#
spring.datasource.url=jdbc:postgresql://patient-manager-postgres:5432/auth_service_db
spring.datasource.username=auth_admin
# load from docker-entrypoint
#spring.datasource.password=
#jwt.secret=