#=============== Auth-Service =======================#
#spring.output.ansi.enabled=local
spring.application.name=auth-service
server.port=4005
##============= JPA and Hibernate Configuration ========#
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never