services:

  # patient-manager-postgres
  patient-manager-postgres:
    deploy:
      resources:
        limits:
          cpus: "0.40"
          memory: 600m
    image: postgres:18
    container_name: patient-manager-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASS
    secrets:
      - POSTGRES_PASS
      - AUTH_DB_PASS
      - PATIENT_DB_PASS
    volumes:
      - ./docker/patient-manager-postgres:/var/lib/postgresql/18/data
      - ./docker/scripts/init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - patient-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  # auth-service
  auth-service:
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 350m
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    networks:
      - patient-network
    ports:
      - "4005:4005"
    environment:
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx256m
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    depends_on:
      patient-manager-postgres:
        condition: service_healthy
    volumes:
      - ./.secrets/auth_db_pass.txt:/run/secrets/AUTH_DB_PASS:ro
      - ./.secrets/jwt_secret.txt:/run/secrets/JWT_SECRET:ro

  # api-gateway
  api-gateway:
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 350m
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    networks:
      - patient-network
    ports:
      - "4004:4004"
      - "5006:5006"
    environment:
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx256m
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      AUTH_SERVICE_URL: ${COMMON_AUTH_SERVICE_URL}
    depends_on:
      - auth-service
      - patient-service

  # patient-service
  patient-service:
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 350m
    build:
      context: ./patient-service/
      dockerfile: Dockerfile
    container_name: patient-service
    networks:
      - patient-network
    ports:
      - "4000:4000"
      - "5005:5005"
    environment:
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx256m
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${COMMON_KAFKA_BOOTSTRAP_SERVERS}
      BILLING_SERVICE_NAME: ${COMMON_BILLING_SERVICE_NAME}
      BILLING_SERVICE_GRPC_PORT: ${COMMON_BILLING_SERVICE_GRPC_PORT}
    env_file:
      - .env
    depends_on:
      patient-manager-postgres:
        condition: service_healthy
    volumes:
      - ./.secrets/patient_db_pass.txt:/run/secrets/PATIENT_DB_PASS:ro

  # billing-service
  billing-service:
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 350m
    build:
      context: ./billing-service
      dockerfile: Dockerfile
    container_name: billing-service
    networks:
      - patient-network
    ports:
      - "4001:4001"
      - "9001:9001"
    environment:
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx256m
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      GRPC_SERVER_PORT: ${COMMON_BILLING_SERVICE_GRPC_PORT}
    depends_on:
      - patient-service

  # analytics-service
  analytics-service:
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 350m
    build:
      context: ./analytics-service
      dockerfile: Dockerfile
    container_name: analytics-service
    networks:
      - patient-network
    ports:
      - "4002:4002"
    environment:
      JAVA_TOOL_OPTIONS: -Xms128m -Xmx256m
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${COMMON_KAFKA_BOOTSTRAP_SERVERS}
    depends_on:
      - api-gateway
      - kafka

  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: 900m
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_HEAP_OPTS: -Xms512m -Xmx512m
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_NODE_ID: 1
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qg==
    networks:
      - patient-network


networks:
  patient-network:
    driver: bridge

secrets:
  POSTGRES_PASS:
    file: .secrets/postgres_pass.txt
  PATIENT_DB_PASS:
    file: .secrets/patient_db_pass.txt
  AUTH_DB_PASS:
    file: .secrets/auth_db_pass.txt
  JWT_SECRET:
    file: .secrets/jwt_secret.txt