---
server:
  port: 4004  # Gateway listens on port 4004

spring:
  output:
    ansi:
      enabled: always
  application:
    name: PatientService
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Route for /auth/** auth-service
            - id: auth-service-route
              uri: http://auth-service:4005
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
                - JwtValidation

            # Route for /api/patients/** to patient-service
            - id: patient-service-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1

            - id: api-docs-patient-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api-docs/patients
              filters:
                - RewritePath=/api-docs/patients,/v3/api-docs

