### POST create a new Patient
POST http://localhost:4004/api/patients
Content-Type: application/json

{
    "name" : "Testerino",
    "lastName" : "Cappucino",
    "email" : "testerino.cappucino@example.com",
    "address" : "alegria siempre viva 124",
    "dateOfBirth" : "1977-03-09"
}

###

