### POST create a new Patient
POST www.localhost:4000/patient
Content-Type: application/json
{
    "name" = "Daniel",
    "lastName" = "Revoir",
    "email" ="daniel.revos@example.com",
    "address" = "025 gideon street",
    "dateOfBirth" = "1977-03-09",
    "registeredDate" = "2023-03-15"
}
###


