### PUT updates an existing Patient by UUID
PUT http://localhost:4004/api/patients/b1a7e8c2-1234-4f56-9abc-1a2b3c4d5e6f
Content-Type: application/json

{
    "id" : "b1a7e8c2-1234-4f56-9abc-1a2b3c4d5e6f",
    "name" : "John",
    "lastName" : "Not Does",
    "email" : "john.notdoes@example.com",
    "address" : "updated john doe example",
    "dateOfBirth" : "1977-03-09"
}

###


