#======== Patient-Service =========================#
#spring.profiles.active=local
spring.output.ansi.enabled=always
spring.application.name=PatientService
server.port=4000
#========= gRPC Billing ============================#
billing.service.name=${BILLING_SERVICE_NAME:test}
billing.service.grpc.port=${BILLING_SERVICE_GRPC_PORT:8000}
#======== swagger =================================#
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
#======== Kafka ===================================#
#spring.kafka.bootstrap-servers=
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
##======= JPA and Hibernate Configuration ========#
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never